# Generated by Django 3.1.4 on 2021-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xogame', '0002_auto_20210723_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='xogame',
            name='boardSize',
            field=models.JSONField(null=True),
        ),
    ]
